4050 #!/usr/bin/perl -w
4051 
4052 # Generate vectors.S, the trap/interrupt entry points.
4053 # There has to be one entry point per interrupt number
4054 # since otherwise there's no way for trap() to discover
4055 # the interrupt number.
4056 
4057 print "# generated by vectors.pl - do not edit\n";
4058 print "# handlers\n";
4059 print ".globl alltraps\n";
4060 for(my $i = 0; $i < 256; $i++){
4061     print ".globl vector$i\n";
4062     print "vector$i:\n";
4063     if(!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
4064         print "  pushl \$0\n";
4065     }
4066     print "  pushl \$$i\n";
4067     print "  jmp alltraps\n";
4068 }
4069 
4070 print "\n# vector table\n";
4071 print ".data\n";
4072 print ".globl vectors\n";
4073 print "vectors:\n";
4074 for(my $i = 0; $i < 256; $i++){
4075     print "  .long vector$i\n";
4076 }
4077 
4078 # sample output:
4079 #   # handlers
4080 #   .globl alltraps
4081 #   .globl vector0
4082 #   vector0:
4083 #     pushl $0
4084 #     pushl $0
4085 #     jmp alltraps
4086 #   ...
4087 #
4088 #   # vector table
4089 #   .data
4090 #   .globl vectors
4091 #   vectors:
4092 #     .long vector0
4093 #     .long vector1
4094 #     .long vector2
4095 #   ...
4096 
4097 
4098 
4099 
